/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/mouse/mouse.module';
import * as import2 from '@angular/common';
import * as import3 from '../../../../src/app/mouse/mouse.service';
class MouseModuleInjector extends import0.ɵNgModuleInjector<import1.MouseModule> {
  _CommonModule_0:import2.CommonModule;
  _MouseModule_1:import1.MouseModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  __MouseService_3:import3.MouseService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _MouseService_3():import3.MouseService {
    if ((this.__MouseService_3 == null)) { (this.__MouseService_3 = new import3.MouseService()); }
    return this.__MouseService_3;
  }
  createInternal():import1.MouseModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._MouseModule_1 = new import1.MouseModule();
    return this._MouseModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.MouseModule)) { return this._MouseModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import3.MouseService)) { return this._MouseService_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MouseModuleNgFactory:import0.NgModuleFactory<import1.MouseModule> = new import0.NgModuleFactory<any>(MouseModuleInjector,import1.MouseModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvbW91c2UvbW91c2UubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvbW91c2UvbW91c2UubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
