/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/modal/modal.module';
import * as import2 from '@angular/common';
import * as import3 from '../../../../src/app/modal/testing/test-modal.module';
import * as import4 from '../../../../src/app/modal/services/component-resolver.service';
import * as import5 from '../../../../src/app/modal/testing/modal.mock.service';
import * as import6 from '../../../../src/app/modal/testing/component-resolver.mock.service';
import * as import7 from '../../../../src/app/modal/services/modal.service';
import * as import8 from './testing/test-modal.component.ngfactory';
import * as import9 from './overlay/overlay.component.ngfactory';
class ModalModuleInjector extends import0.ɵNgModuleInjector<import1.ModalModule> {
  _CommonModule_0:import2.CommonModule;
  _TestModalModule_1:import3.TestModalModule;
  _ModalModule_2:import1.ModalModule;
  __NgLocalization_3:import2.NgLocaleLocalization;
  __ComponentResolverService_4:import4.ComponentResolverService;
  __ModalMockService_5:import5.ModalMockService;
  __ComponentResolverMockService_6:import6.ComponentResolverMockService;
  __ModalService_7:import7.ModalService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import8.TestModalComponentNgFactory,
      import9.OverlayComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_3():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  get _ComponentResolverService_4():import4.ComponentResolverService {
    if ((this.__ComponentResolverService_4 == null)) { (this.__ComponentResolverService_4 = new import4.ComponentResolverService(this.componentFactoryResolver)); }
    return this.__ComponentResolverService_4;
  }
  get _ModalMockService_5():import5.ModalMockService {
    if ((this.__ModalMockService_5 == null)) { (this.__ModalMockService_5 = new import5.ModalMockService(this._ComponentResolverService_4)); }
    return this.__ModalMockService_5;
  }
  get _ComponentResolverMockService_6():import6.ComponentResolverMockService {
    if ((this.__ComponentResolverMockService_6 == null)) { (this.__ComponentResolverMockService_6 = new import6.ComponentResolverMockService(this.componentFactoryResolver)); }
    return this.__ComponentResolverMockService_6;
  }
  get _ModalService_7():import7.ModalService {
    if ((this.__ModalService_7 == null)) { (this.__ModalService_7 = new import7.ModalService(this._ComponentResolverService_4)); }
    return this.__ModalService_7;
  }
  createInternal():import1.ModalModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._TestModalModule_1 = new import3.TestModalModule();
    this._ModalModule_2 = new import1.ModalModule();
    return this._ModalModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.TestModalModule)) { return this._TestModalModule_1; }
    if ((token === import1.ModalModule)) { return this._ModalModule_2; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import4.ComponentResolverService)) { return this._ComponentResolverService_4; }
    if ((token === import5.ModalMockService)) { return this._ModalMockService_5; }
    if ((token === import6.ComponentResolverMockService)) { return this._ComponentResolverMockService_6; }
    if ((token === import7.ModalService)) { return this._ModalService_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ModalModuleNgFactory:import0.NgModuleFactory<import1.ModalModule> = new import0.NgModuleFactory<any>(ModalModuleInjector,import1.ModalModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvbW9kYWwvbW9kYWwubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvbW9kYWwvbW9kYWwubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
