/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/api/api.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/http';
import * as import4 from '../../../../src/app/api/api.service';
class ApiModuleInjector extends import0.ɵNgModuleInjector<import1.ApiModule> {
  _CommonModule_0:import2.CommonModule;
  _HttpModule_1:import3.HttpModule;
  _JsonpModule_2:import3.JsonpModule;
  _ApiModule_3:import1.ApiModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  __BrowserXhr_5:import3.BrowserXhr;
  __ResponseOptions_6:import3.BaseResponseOptions;
  __XSRFStrategy_7:any;
  __XHRBackend_8:import3.XHRBackend;
  __RequestOptions_9:import3.BaseRequestOptions;
  __Http_10:any;
  __ɵg_11:import3.ɵg;
  __JSONPBackend_12:import3.ɵa;
  __Jsonp_13:any;
  __ApiService_14:import4.ApiService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  get _BrowserXhr_5():import3.BrowserXhr {
    if ((this.__BrowserXhr_5 == null)) { (this.__BrowserXhr_5 = new import3.BrowserXhr()); }
    return this.__BrowserXhr_5;
  }
  get _ResponseOptions_6():import3.BaseResponseOptions {
    if ((this.__ResponseOptions_6 == null)) { (this.__ResponseOptions_6 = new import3.BaseResponseOptions()); }
    return this.__ResponseOptions_6;
  }
  get _XSRFStrategy_7():any {
    if ((this.__XSRFStrategy_7 == null)) { (this.__XSRFStrategy_7 = import3.ɵb()); }
    return this.__XSRFStrategy_7;
  }
  get _XHRBackend_8():import3.XHRBackend {
    if ((this.__XHRBackend_8 == null)) { (this.__XHRBackend_8 = new import3.XHRBackend(this._BrowserXhr_5,this._ResponseOptions_6,this._XSRFStrategy_7)); }
    return this.__XHRBackend_8;
  }
  get _RequestOptions_9():import3.BaseRequestOptions {
    if ((this.__RequestOptions_9 == null)) { (this.__RequestOptions_9 = new import3.BaseRequestOptions()); }
    return this.__RequestOptions_9;
  }
  get _Http_10():any {
    if ((this.__Http_10 == null)) { (this.__Http_10 = import3.ɵc(this._XHRBackend_8,this._RequestOptions_9)); }
    return this.__Http_10;
  }
  get _ɵg_11():import3.ɵg {
    if ((this.__ɵg_11 == null)) { (this.__ɵg_11 = new import3.ɵg()); }
    return this.__ɵg_11;
  }
  get _JSONPBackend_12():import3.ɵa {
    if ((this.__JSONPBackend_12 == null)) { (this.__JSONPBackend_12 = new import3.ɵa(this._ɵg_11,this._ResponseOptions_6)); }
    return this.__JSONPBackend_12;
  }
  get _Jsonp_13():any {
    if ((this.__Jsonp_13 == null)) { (this.__Jsonp_13 = import3.ɵd(this._JSONPBackend_12,this._RequestOptions_9)); }
    return this.__Jsonp_13;
  }
  get _ApiService_14():import4.ApiService {
    if ((this.__ApiService_14 == null)) { (this.__ApiService_14 = new import4.ApiService(this._Http_10,this._Jsonp_13)); }
    return this.__ApiService_14;
  }
  createInternal():import1.ApiModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._HttpModule_1 = new import3.HttpModule();
    this._JsonpModule_2 = new import3.JsonpModule();
    this._ApiModule_3 = new import1.ApiModule();
    return this._ApiModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.HttpModule)) { return this._HttpModule_1; }
    if ((token === import3.JsonpModule)) { return this._JsonpModule_2; }
    if ((token === import1.ApiModule)) { return this._ApiModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.BrowserXhr)) { return this._BrowserXhr_5; }
    if ((token === import3.ResponseOptions)) { return this._ResponseOptions_6; }
    if ((token === import3.XSRFStrategy)) { return this._XSRFStrategy_7; }
    if ((token === import3.XHRBackend)) { return this._XHRBackend_8; }
    if ((token === import3.RequestOptions)) { return this._RequestOptions_9; }
    if ((token === import3.Http)) { return this._Http_10; }
    if ((token === import3.ɵg)) { return this._ɵg_11; }
    if ((token === import3.JSONPBackend)) { return this._JSONPBackend_12; }
    if ((token === import3.Jsonp)) { return this._Jsonp_13; }
    if ((token === import4.ApiService)) { return this._ApiService_14; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ApiModuleNgFactory:import0.NgModuleFactory<import1.ApiModule> = new import0.NgModuleFactory<any>(ApiModuleInjector,import1.ApiModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvYXBpL2FwaS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc3RlcmVvZ3JhcGgvZnJhbWV3b3JrL2NvcmUvc3JjL2FwcC9hcGkvYXBpLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
