/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './modal/modal.component.ngfactory';
import * as import2 from '../../../src/app/modal/modal.component';
import * as import3 from '../../../src/app/modal/services/modal.service';
import * as import4 from '../../../src/app/app.component';
const styles_AppComponent:any[] = [''];
export const RenderType_AppComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'modal',([] as any[]),(null as any),(null as any),(null as any),import1.View_ModalComponent_0,import1.RenderType_ModalComponent)),
    import0.ɵdid(4308992,(null as any),0,import2.ModalComponent,[import3.ModalService],(null as any),(null as any)),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import4.AppComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.openModal()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Modal']))
  ]
  ,(ck,v) => {
    ck(v,3,0);
  },(ck,v) => {
    var co:import4.AppComponent = v.component;
    const currVal_0:any = co.title;
    ck(v,1,0,currVal_0);
  });
}
function View_AppComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import0.ɵdid(49152,(null as any),0,import4.AppComponent,[import3.ModalService],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import4.AppComponent> = import0.ɵccf('app-root',import4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPnt7dGl0bGV9fTwvaDE+PG1vZGFsPjwvbW9kYWw+PGJ1dHRvbiAoY2xpY2spPVwib3Blbk1vZGFsKClcIj5Nb2RhbDwvYnV0dG9uPiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBYztnQkFBQTtNQUFlO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQVE7UUFBQTtRQUFBO01BQUE7TUFBUjtJQUFBO0lBQThCOzs7SUFBN0M7OztJQUFkO0lBQUE7Ozs7O0lDQUo7Z0JBQUE7Ozs7In0=
