/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '@angular/forms';
import * as import5 from '@angular/http';
import * as import6 from '../../../src/app/modal/testing/test-modal.module';
import * as import7 from '../../../src/app/modal/modal.module';
import * as import8 from '../../../src/app/modal/services/component-resolver.service';
import * as import9 from '../../../src/app/modal/testing/modal.mock.service';
import * as import10 from '../../../src/app/modal/testing/component-resolver.mock.service';
import * as import11 from '../../../src/app/modal/services/modal.service';
import * as import12 from './modal/testing/test-modal.component.ngfactory';
import * as import13 from './modal/overlay/overlay.component.ngfactory';
import * as import14 from './app.component.ngfactory';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _APP_INITIALIZER_2:any[];
  _ApplicationInitStatus_3:import0.ApplicationInitStatus;
  _ɵf_4:import0.ɵf;
  _ApplicationRef_5:any;
  _ApplicationModule_6:import0.ApplicationModule;
  _BrowserModule_7:import3.BrowserModule;
  _ɵba_8:import4.ɵba;
  _FormsModule_9:import4.FormsModule;
  _HttpModule_10:import5.HttpModule;
  _TestModalModule_11:import6.TestModalModule;
  _ModalModule_12:import7.ModalModule;
  _AppModule_13:import1.AppModule;
  __LOCALE_ID_14:any;
  __NgLocalization_15:import2.NgLocaleLocalization;
  __Compiler_16:import0.Compiler;
  __APP_ID_17:any;
  __IterableDiffers_18:any;
  __KeyValueDiffers_19:any;
  __DomSanitizer_20:import3.ɵe;
  __Sanitizer_21:any;
  __HAMMER_GESTURE_CONFIG_22:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_23:any[];
  __EventManager_24:import3.EventManager;
  __ɵDomSharedStylesHost_25:import3.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_26:import3.ɵDomRendererFactory2;
  __RendererFactory2_27:any;
  __ɵSharedStylesHost_28:any;
  __Testability_29:import0.Testability;
  __Meta_30:import3.Meta;
  __Title_31:import3.Title;
  __ɵi_32:import4.ɵi;
  __BrowserXhr_33:import5.BrowserXhr;
  __ResponseOptions_34:import5.BaseResponseOptions;
  __XSRFStrategy_35:any;
  __XHRBackend_36:import5.XHRBackend;
  __RequestOptions_37:import5.BaseRequestOptions;
  __Http_38:any;
  __ComponentResolverService_39:import8.ComponentResolverService;
  __ModalMockService_40:import9.ModalMockService;
  __ComponentResolverMockService_41:import10.ComponentResolverMockService;
  __ModalService_42:import11.ModalService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import12.TestModalComponentNgFactory,
      import13.OverlayComponentNgFactory,
      import14.AppComponentNgFactory
    ]
    ,[import14.AppComponentNgFactory]);
  }
  get _LOCALE_ID_14():any {
    if ((this.__LOCALE_ID_14 == null)) { (this.__LOCALE_ID_14 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_14;
  }
  get _NgLocalization_15():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_15 == null)) { (this.__NgLocalization_15 = new import2.NgLocaleLocalization(this._LOCALE_ID_14)); }
    return this.__NgLocalization_15;
  }
  get _Compiler_16():import0.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import0.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import0.ɵg()); }
    return this.__APP_ID_17;
  }
  get _IterableDiffers_18():any {
    if ((this.__IterableDiffers_18 == null)) { (this.__IterableDiffers_18 = import0.ɵl()); }
    return this.__IterableDiffers_18;
  }
  get _KeyValueDiffers_19():any {
    if ((this.__KeyValueDiffers_19 == null)) { (this.__KeyValueDiffers_19 = import0.ɵm()); }
    return this.__KeyValueDiffers_19;
  }
  get _DomSanitizer_20():import3.ɵe {
    if ((this.__DomSanitizer_20 == null)) { (this.__DomSanitizer_20 = new import3.ɵe(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_20;
  }
  get _Sanitizer_21():any {
    if ((this.__Sanitizer_21 == null)) { (this.__Sanitizer_21 = this._DomSanitizer_20); }
    return this.__Sanitizer_21;
  }
  get _HAMMER_GESTURE_CONFIG_22():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_22 == null)) { (this.__HAMMER_GESTURE_CONFIG_22 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_22;
  }
  get _EVENT_MANAGER_PLUGINS_23():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_23 == null)) { (this.__EVENT_MANAGER_PLUGINS_23 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_22)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_23;
  }
  get _EventManager_24():import3.EventManager {
    if ((this.__EventManager_24 == null)) { (this.__EventManager_24 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_23,this.parent.get(import0.NgZone))); }
    return this.__EventManager_24;
  }
  get _ɵDomSharedStylesHost_25():import3.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_25 == null)) { (this.__ɵDomSharedStylesHost_25 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_25;
  }
  get _ɵDomRendererFactory2_26():import3.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_26 == null)) { (this.__ɵDomRendererFactory2_26 = new import3.ɵDomRendererFactory2(this._EventManager_24,this._ɵDomSharedStylesHost_25)); }
    return this.__ɵDomRendererFactory2_26;
  }
  get _RendererFactory2_27():any {
    if ((this.__RendererFactory2_27 == null)) { (this.__RendererFactory2_27 = this._ɵDomRendererFactory2_26); }
    return this.__RendererFactory2_27;
  }
  get _ɵSharedStylesHost_28():any {
    if ((this.__ɵSharedStylesHost_28 == null)) { (this.__ɵSharedStylesHost_28 = this._ɵDomSharedStylesHost_25); }
    return this.__ɵSharedStylesHost_28;
  }
  get _Testability_29():import0.Testability {
    if ((this.__Testability_29 == null)) { (this.__Testability_29 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_29;
  }
  get _Meta_30():import3.Meta {
    if ((this.__Meta_30 == null)) { (this.__Meta_30 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_30;
  }
  get _Title_31():import3.Title {
    if ((this.__Title_31 == null)) { (this.__Title_31 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_31;
  }
  get _ɵi_32():import4.ɵi {
    if ((this.__ɵi_32 == null)) { (this.__ɵi_32 = new import4.ɵi()); }
    return this.__ɵi_32;
  }
  get _BrowserXhr_33():import5.BrowserXhr {
    if ((this.__BrowserXhr_33 == null)) { (this.__BrowserXhr_33 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_33;
  }
  get _ResponseOptions_34():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_34 == null)) { (this.__ResponseOptions_34 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_34;
  }
  get _XSRFStrategy_35():any {
    if ((this.__XSRFStrategy_35 == null)) { (this.__XSRFStrategy_35 = import5.ɵb()); }
    return this.__XSRFStrategy_35;
  }
  get _XHRBackend_36():import5.XHRBackend {
    if ((this.__XHRBackend_36 == null)) { (this.__XHRBackend_36 = new import5.XHRBackend(this._BrowserXhr_33,this._ResponseOptions_34,this._XSRFStrategy_35)); }
    return this.__XHRBackend_36;
  }
  get _RequestOptions_37():import5.BaseRequestOptions {
    if ((this.__RequestOptions_37 == null)) { (this.__RequestOptions_37 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_37;
  }
  get _Http_38():any {
    if ((this.__Http_38 == null)) { (this.__Http_38 = import5.ɵc(this._XHRBackend_36,this._RequestOptions_37)); }
    return this.__Http_38;
  }
  get _ComponentResolverService_39():import8.ComponentResolverService {
    if ((this.__ComponentResolverService_39 == null)) { (this.__ComponentResolverService_39 = new import8.ComponentResolverService(this.componentFactoryResolver)); }
    return this.__ComponentResolverService_39;
  }
  get _ModalMockService_40():import9.ModalMockService {
    if ((this.__ModalMockService_40 == null)) { (this.__ModalMockService_40 = new import9.ModalMockService(this._ComponentResolverService_39)); }
    return this.__ModalMockService_40;
  }
  get _ComponentResolverMockService_41():import10.ComponentResolverMockService {
    if ((this.__ComponentResolverMockService_41 == null)) { (this.__ComponentResolverMockService_41 = new import10.ComponentResolverMockService(this.componentFactoryResolver)); }
    return this.__ComponentResolverMockService_41;
  }
  get _ModalService_42():import11.ModalService {
    if ((this.__ModalService_42 == null)) { (this.__ModalService_42 = new import11.ModalService(this._ComponentResolverService_39)); }
    return this.__ModalService_42;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import3.ɵa();
    this._APP_INITIALIZER_2 = [
      import0.ɵo,
      import3.ɵc(this.parent.get(import3.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_3 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_2);
    this._ɵf_4 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_3);
    this._ApplicationRef_5 = this._ɵf_4;
    this._ApplicationModule_6 = new import0.ApplicationModule(this._ApplicationRef_5);
    this._BrowserModule_7 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._ɵba_8 = new import4.ɵba();
    this._FormsModule_9 = new import4.FormsModule();
    this._HttpModule_10 = new import5.HttpModule();
    this._TestModalModule_11 = new import6.TestModalModule();
    this._ModalModule_12 = new import7.ModalModule();
    this._AppModule_13 = new import1.AppModule();
    return this._AppModule_13;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_2; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_3; }
    if ((token === import0.ɵf)) { return this._ɵf_4; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_5; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_6; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_7; }
    if ((token === import4.ɵba)) { return this._ɵba_8; }
    if ((token === import4.FormsModule)) { return this._FormsModule_9; }
    if ((token === import5.HttpModule)) { return this._HttpModule_10; }
    if ((token === import6.TestModalModule)) { return this._TestModalModule_11; }
    if ((token === import7.ModalModule)) { return this._ModalModule_12; }
    if ((token === import1.AppModule)) { return this._AppModule_13; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_14; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_15; }
    if ((token === import0.Compiler)) { return this._Compiler_16; }
    if ((token === import0.APP_ID)) { return this._APP_ID_17; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_18; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_19; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_20; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_21; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_22; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_23; }
    if ((token === import3.EventManager)) { return this._EventManager_24; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_25; }
    if ((token === import3.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_26; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_27; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_28; }
    if ((token === import0.Testability)) { return this._Testability_29; }
    if ((token === import3.Meta)) { return this._Meta_30; }
    if ((token === import3.Title)) { return this._Title_31; }
    if ((token === import4.ɵi)) { return this._ɵi_32; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_33; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_34; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_35; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_36; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_37; }
    if ((token === import5.Http)) { return this._Http_38; }
    if ((token === import8.ComponentResolverService)) { return this._ComponentResolverService_39; }
    if ((token === import9.ModalMockService)) { return this._ModalMockService_40; }
    if ((token === import10.ComponentResolverMockService)) { return this._ComponentResolverMockService_41; }
    if ((token === import11.ModalService)) { return this._ModalService_42; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_4.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_25 && this._ɵDomSharedStylesHost_25.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
