/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/modal/overlay/overlay.component';
const styles_OverlayComponent:any[] = ['[_nghost-%COMP%]   .overlay[_ngcontent-%COMP%]{position:fixed;z-index:9998;background-color:rgba(0,0,0,.5);height:100%;width:100%;top:0;left:0}[_nghost-%COMP%]   .overlay-blocking[_ngcontent-%COMP%]{pointer-events:none}'];
export const RenderType_OverlayComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_OverlayComponent,
  data: {}
}
);
export function View_OverlayComponent_0(l:any):import0.ɵViewDefinition {
      return import0.ɵvid(0,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'overlay'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.OverlayComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.click()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
  },(null as any),(null as any)))],(null as any),(null as any));
}
function View_OverlayComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-overlay',([] as any[]),(null as any),(null as any),(null as any),View_OverlayComponent_0,RenderType_OverlayComponent)),
    import0.ɵdid(49152,(null as any),0,import1.OverlayComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const OverlayComponentNgFactory:import0.ComponentFactory<import1.OverlayComponent> = import0.ɵccf('app-overlay',import1.OverlayComponent,View_OverlayComponent_Host_0,{},{onClick: 'onClick'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvbW9kYWwvb3ZlcmxheS9vdmVybGF5LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL21vZGFsL292ZXJsYXkvb3ZlcmxheS5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL21vZGFsL292ZXJsYXkvb3ZlcmxheS5jb21wb25lbnQudHMuT3ZlcmxheUNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvc3RlcmVvZ3JhcGgvZnJhbWV3b3JrL2NvcmUvc3JjL2FwcC9tb2RhbC9vdmVybGF5L292ZXJsYXkuY29tcG9uZW50LnRzLk92ZXJsYXlDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IChjbGljayk9XCJjbGljaygpXCIgY2xhc3M9XCJvdmVybGF5XCI+PC9kaXY+IiwiPGFwcC1vdmVybGF5PjwvYXBwLW92ZXJsYXk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZCQ0FBO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFBSztRQUFBO1FBQUE7TUFBQTtNQUFMO0VBQUE7Ozs7SUNBQTtnQkFBQTs7OzsifQ==
