/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/modal/testing/test-modal.component';
const styles_TestModalComponent:any[] = ([] as any[]);
export const RenderType_TestModalComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TestModalComponent,
  data: {}
}
);
export function View_TestModalComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),2,'div',[[
        'id',
        'test-modal-component'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Test modal component']))
  ]
  ,(null as any),(null as any));
}
function View_TestModalComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_TestModalComponent_0,RenderType_TestModalComponent)),
    import0.ɵdid(49152,(null as any),0,import1.TestModalComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TestModalComponentNgFactory:import0.ComponentFactory<import1.TestModalComponent> = import0.ɵccf('ng-component',import1.TestModalComponent,View_TestModalComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3N0ZXJlb2dyYXBoL2ZyYW1ld29yay9jb3JlL3NyYy9hcHAvbW9kYWwvdGVzdGluZy90ZXN0LW1vZGFsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL21vZGFsL3Rlc3RpbmcvdGVzdC1tb2RhbC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL21vZGFsL3Rlc3RpbmcvdGVzdC1tb2RhbC5jb21wb25lbnQudHMuVGVzdE1vZGFsQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9zdGVyZW9ncmFwaC9mcmFtZXdvcmsvY29yZS9zcmMvYXBwL21vZGFsL3Rlc3RpbmcvdGVzdC1tb2RhbC5jb21wb25lbnQudHMuVGVzdE1vZGFsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBpZD1cInRlc3QtbW9kYWwtY29tcG9uZW50XCI+PGgxPlRlc3QgbW9kYWwgY29tcG9uZW50PC9oMT48L2Rpdj4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQStCO0lBQUk7Ozs7OztJQ0FuQztnQkFBQTs7OzsifQ==
